[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink/contracts"]
#La línea que sigue permitiría a Solidty ejecutar código en nuestra máquina. 
ffi = true 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
